
// Generated by Cadence Genus(TM) Synthesis Solution 21.12-s068_1
// Generated on: Jan 31 2026 15:38:51 +07 (Jan 31 2026 08:38:51 UTC)

// Verification Directory fv/ALU 

`define ONE_HOT_MUX

module fadder_1bit(a, b, cin, s, cout);
  input a, b, cin;
  output s, cout;
  wire a, b, cin;
  wire s, cout;
  wire n_3, n_6, n_7;
  xor g1 (n_3, a, b);
  xor g2 (s, n_3, cin);
  and g3 (n_6, a, b);
  and g5 (n_7, cin, n_3);
  or g6 (cout, n_6, n_7);
endmodule

module fadder_8bit(a, b, cin, s, cout);
  input [7:0] a, b;
  input cin;
  output [7:0] s;
  output cout;
  wire [7:0] a, b;
  wire cin;
  wire [7:0] s;
  wire cout;
  wire cin1, cin2, cin3, cin4, cin5, cin6, cin7;
  fadder_1bit F0(.a (a[0]), .b (b[0]), .cin (cin), .s (s[0]), .cout (cin1));
  fadder_1bit F1(.a (a[1]), .b (b[1]), .cin (cin1), .s (s[1]), .cout (cin2));
  fadder_1bit F2(.a (a[2]), .b (b[2]), .cin (cin2), .s (s[2]), .cout (cin3));
  fadder_1bit F3(.a (a[3]), .b (b[3]), .cin (cin3), .s (s[3]), .cout (cin4));
  fadder_1bit F4(.a (a[4]), .b (b[4]), .cin (cin4), .s (s[4]), .cout (cin5));
  fadder_1bit F5(.a (a[5]), .b (b[5]), .cin (cin5), .s (s[5]), .cout (cin6));
  fadder_1bit F6(.a (a[6]), .b (b[6]), .cin (cin6), .s (s[6]), .cout (cin7));
  fadder_1bit F7(.a (a[7]), .b (b[7]), .cin (cin7), .s (s[7]), .cout (cout));
endmodule

module fsubtrator_1bit(a, b, bin, d, bout);
  input a, b, bin;
  output d, bout;
  wire a, b, bin;
  wire d, bout;
  wire n_3, n_5, n_7, n_8, n_9;
  xor g1 (n_3, a, b);
  xor g2 (d, n_3, bin);
  not g3 (n_5, a);
  and g4 (n_8, n_5, b);
  not g6 (n_7, n_3);
  and g7 (n_9, bin, n_7);
  or g8 (bout, n_8, n_9);
endmodule

module fsubtrator_8bit(a, b, bin, d, bout);
  input [7:0] a, b;
  input bin;
  output [7:0] d;
  output bout;
  wire [7:0] a, b;
  wire bin;
  wire [7:0] d;
  wire bout;
  wire bin1, bin2, bin3, bin4, bin5, bin6, bin7;
  fsubtrator_1bit D0(.a (a[0]), .b (b[0]), .bin (bin), .d (d[0]), .bout (bin1));
  fsubtrator_1bit D1(.a (a[1]), .b (b[1]), .bin (bin1), .d (d[1]), .bout (bin2));
  fsubtrator_1bit D2(.a (a[2]), .b (b[2]), .bin (bin2), .d (d[2]), .bout (bin3));
  fsubtrator_1bit D3(.a (a[3]), .b (b[3]), .bin (bin3), .d (d[3]), .bout (bin4));
  fsubtrator_1bit D4(.a (a[4]), .b (b[4]), .bin (bin4), .d (d[4]), .bout (bin5));
  fsubtrator_1bit D5(.a (a[5]), .b (b[5]), .bin (bin5), .d (d[5]), .bout (bin6));
  fsubtrator_1bit D6(.a (a[6]), .b (b[6]), .bin (bin6), .d (d[6]), .bout (bin7));
  fsubtrator_1bit D7(.a (a[7]), .b (b[7]), .bin (bin7), .d (d[7]), .bout (bout));
endmodule

module half_adder_1bit(a, b, s, cout);
  input a, b;
  output s, cout;
  wire a, b;
  wire s, cout;
  xor g1 (s, a, b);
  and g2 (cout, a, b);
endmodule

module multiply(in_a, in_b, mul_out, overflow);
  input [3:0] in_a, in_b;
  output [7:0] mul_out;
  output overflow;
  wire [3:0] in_a, in_b;
  wire [7:0] mul_out;
  wire overflow;
  wire [3:0] c_r1;
  wire [3:0] s_r1;
  wire [3:0] c_r2;
  wire [3:0] s_r2;
  wire [3:0] c_r3;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  half_adder_1bit H0_r1(.a (n_1), .b (n_2), .s (mul_out[1]), .cout (c_r1[0]));
  fadder_1bit H1_r1(.a (n_3), .b (n_4), .cin (c_r1[0]), .s (s_r1[1]), .cout (c_r1[1]));
  fadder_1bit H2_r1(.a (n_5), .b (n_6), .cin (c_r1[1]), .s (s_r1[2]), .cout (c_r1[2]));
  half_adder_1bit H3_r1(.a (n_7), .b (c_r1[2]), .s (s_r1[3]), .cout (c_r1[3]));
  half_adder_1bit H4_r2(.a (n_8), .b (s_r1[1]), .s (mul_out[2]), .cout (c_r2[0]));
  fadder_1bit H5_r2(.a (n_9), .b (s_r1[2]), .cin (c_r2[0]), .s (s_r2[1]), .cout (c_r2[1]));
  fadder_1bit H6_r2(.a (n_10), .b (s_r1[3]), .cin (c_r2[1]), .s (s_r2[2]), .cout (c_r2[2]));
  fadder_1bit H7_r2(.a (n_11), .b (c_r1[3]), .cin (c_r2[2]), .s (s_r2[3]), .cout (c_r2[3]));
  half_adder_1bit H8_r3(.a (n_12), .b (s_r2[1]), .s (mul_out[3]), .cout (c_r3[0]));
  fadder_1bit H9_r3(.a (n_13), .b (s_r2[2]), .cin (c_r3[0]), .s (mul_out[4]), .cout (c_r3[1]));
  fadder_1bit H10_r3(.a (n_14), .b (s_r2[3]), .cin (c_r3[1]), .s (mul_out[5]), .cout (c_r3[2]));
  fadder_1bit H11_r3(.a (n_15), .b (c_r2[3]), .cin (c_r3[2]), .s (mul_out[6]), .cout (mul_out[7]));
  and g1 (mul_out[0], in_a[0], in_b[0]);
  and g2 (n_1, in_a[1], in_b[0]);
  and g3 (n_2, in_a[0], in_b[1]);
  and g4 (n_3, in_a[2], in_b[0]);
  and g5 (n_4, in_a[1], in_b[1]);
  and g6 (n_5, in_a[3], in_b[0]);
  and g7 (n_6, in_a[2], in_b[1]);
  and g8 (n_7, in_a[3], in_b[1]);
  and g9 (n_8, in_a[0], in_b[2]);
  and g10 (n_9, in_a[1], in_b[2]);
  and g11 (n_10, in_a[2], in_b[2]);
  and g12 (n_11, in_a[3], in_b[2]);
  and g13 (n_12, in_a[0], in_b[3]);
  and g14 (n_13, in_a[1], in_b[3]);
  and g15 (n_14, in_a[2], in_b[3]);
  and g16 (n_15, in_a[3], in_b[3]);
  or g20 (overflow, mul_out[7], mul_out[6], mul_out[5], mul_out[4]);
endmodule

module case_box(in_0, out_0);
  input [2:0] in_0;
  output [2:0] out_0;
  wire [2:0] in_0;
  wire [2:0] out_0;
  wire n_6, n_7, n_9, n_19;
  nand g1 (n_7, in_0[2], n_19, in_0[0]);
  nand g2 (n_9, in_0[2], in_0[1], n_6);
  not g3 (out_0[2], n_7);
  not g4 (out_0[1], n_9);
  nor g5 (out_0[0], out_0[1], out_0[2]);
  not g6 (n_19, in_0[1]);
  not g9 (n_6, in_0[0]);
endmodule

module mux(ctl, in_0, in_1, in_2, z);
  input [2:0] ctl;
  input in_0, in_1, in_2;
  output z;
  wire [2:0] ctl;
  wire in_0, in_1, in_2;
  wire z;
  CDN_mux3 g1(.sel0 (ctl[2]), .data0 (in_0), .sel1 (ctl[1]), .data1 (in_1), .sel2 (ctl[0]), .data2 (in_2), .z (z));
endmodule

module mux_1(ctl, in_0, in_1, in_2, z);
  input [2:0] ctl;
  input [7:0] in_0, in_1, in_2;
  output [7:0] z;
  wire [2:0] ctl;
  wire [7:0] in_0, in_1, in_2;
  wire [7:0] z;
  CDN_mux3 g1(.sel0 (ctl[2]), .data0 (in_0[7]), .sel1 (ctl[1]), .data1 (in_1[7]), .sel2 (ctl[0]), .data2 (in_2[7]), .z (z[7]));
  CDN_mux3 g2(.sel0 (ctl[2]), .data0 (in_0[6]), .sel1 (ctl[1]), .data1 (in_1[6]), .sel2 (ctl[0]), .data2 (in_2[6]), .z (z[6]));
  CDN_mux3 g3(.sel0 (ctl[2]), .data0 (in_0[5]), .sel1 (ctl[1]), .data1 (in_1[5]), .sel2 (ctl[0]), .data2 (in_2[5]), .z (z[5]));
  CDN_mux3 g4(.sel0 (ctl[2]), .data0 (in_0[4]), .sel1 (ctl[1]), .data1 (in_1[4]), .sel2 (ctl[0]), .data2 (in_2[4]), .z (z[4]));
  CDN_mux3 g5(.sel0 (ctl[2]), .data0 (in_0[3]), .sel1 (ctl[1]), .data1 (in_1[3]), .sel2 (ctl[0]), .data2 (in_2[3]), .z (z[3]));
  CDN_mux3 g6(.sel0 (ctl[2]), .data0 (in_0[2]), .sel1 (ctl[1]), .data1 (in_1[2]), .sel2 (ctl[0]), .data2 (in_2[2]), .z (z[2]));
  CDN_mux3 g7(.sel0 (ctl[2]), .data0 (in_0[1]), .sel1 (ctl[1]), .data1 (in_1[1]), .sel2 (ctl[0]), .data2 (in_2[1]), .z (z[1]));
  CDN_mux3 g8(.sel0 (ctl[2]), .data0 (in_0[0]), .sel1 (ctl[1]), .data1 (in_1[0]), .sel2 (ctl[0]), .data2 (in_2[0]), .z (z[0]));
endmodule

module shifter_8bit(in_a, input_carry, opcode, shift_out, shift_cf);
  input [7:0] in_a;
  input input_carry;
  input [2:0] opcode;
  output [7:0] shift_out;
  output shift_cf;
  wire [7:0] in_a;
  wire input_carry;
  wire [2:0] opcode;
  wire [7:0] shift_out;
  wire shift_cf;
  wire n_13, n_14, n_15, n_16, n_19;
  case_box ctl_opcode_205_10(.in_0 (opcode), .out_0 ({n_13, n_14, n_19}));
  mux mux_shift_cf_205_10(.ctl ({n_13, n_14, n_16}), .in_0 (in_a[7]), .in_1 (in_a[0]), .in_2 (1'b0), .z (shift_cf));
  mux_1 mux_shift_out_205_10(.ctl ({n_13, n_14, n_19}), .in_0 ({in_a[6:0], input_carry}), .in_1 ({input_carry, in_a[7:1]}), .in_2 (8'b0), .z (shift_out));
  or g1 (n_15, n_13, n_14);
  not g2 (n_16, n_15);
endmodule

module bmux(ctl, in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7, z);
  input [2:0] ctl;
  input in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  output z;
  wire [2:0] ctl;
  wire in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  wire z;
  CDN_bmux8 g1(.sel0 (ctl[0]), .data0 (in_0), .data1 (in_1), .sel1 (ctl[1]), .data2 (in_2), .data3 (in_3), .sel2 (ctl[2]), .data4 (in_4), .data5 (in_5), .data6 (in_6), .data7 (in_7), .z (z));
endmodule

module bmux_2(ctl, in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7, z);
  input [2:0] ctl;
  input [7:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  output [7:0] z;
  wire [2:0] ctl;
  wire [7:0] in_0, in_1, in_2, in_3, in_4, in_5, in_6, in_7;
  wire [7:0] z;
  CDN_bmux8 g1(.sel0 (ctl[0]), .data0 (in_0[7]), .data1 (in_1[7]), .sel1 (ctl[1]), .data2 (in_2[7]), .data3 (in_3[7]), .sel2 (ctl[2]), .data4 (in_4[7]), .data5 (in_5[7]), .data6 (in_6[7]), .data7 (in_7[7]), .z (z[7]));
  CDN_bmux8 g2(.sel0 (ctl[0]), .data0 (in_0[6]), .data1 (in_1[6]), .sel1 (ctl[1]), .data2 (in_2[6]), .data3 (in_3[6]), .sel2 (ctl[2]), .data4 (in_4[6]), .data5 (in_5[6]), .data6 (in_6[6]), .data7 (in_7[6]), .z (z[6]));
  CDN_bmux8 g3(.sel0 (ctl[0]), .data0 (in_0[5]), .data1 (in_1[5]), .sel1 (ctl[1]), .data2 (in_2[5]), .data3 (in_3[5]), .sel2 (ctl[2]), .data4 (in_4[5]), .data5 (in_5[5]), .data6 (in_6[5]), .data7 (in_7[5]), .z (z[5]));
  CDN_bmux8 g4(.sel0 (ctl[0]), .data0 (in_0[4]), .data1 (in_1[4]), .sel1 (ctl[1]), .data2 (in_2[4]), .data3 (in_3[4]), .sel2 (ctl[2]), .data4 (in_4[4]), .data5 (in_5[4]), .data6 (in_6[4]), .data7 (in_7[4]), .z (z[4]));
  CDN_bmux8 g5(.sel0 (ctl[0]), .data0 (in_0[3]), .data1 (in_1[3]), .sel1 (ctl[1]), .data2 (in_2[3]), .data3 (in_3[3]), .sel2 (ctl[2]), .data4 (in_4[3]), .data5 (in_5[3]), .data6 (in_6[3]), .data7 (in_7[3]), .z (z[3]));
  CDN_bmux8 g6(.sel0 (ctl[0]), .data0 (in_0[2]), .data1 (in_1[2]), .sel1 (ctl[1]), .data2 (in_2[2]), .data3 (in_3[2]), .sel2 (ctl[2]), .data4 (in_4[2]), .data5 (in_5[2]), .data6 (in_6[2]), .data7 (in_7[2]), .z (z[2]));
  CDN_bmux8 g7(.sel0 (ctl[0]), .data0 (in_0[1]), .data1 (in_1[1]), .sel1 (ctl[1]), .data2 (in_2[1]), .data3 (in_3[1]), .sel2 (ctl[2]), .data4 (in_4[1]), .data5 (in_5[1]), .data6 (in_6[1]), .data7 (in_7[1]), .z (z[1]));
  CDN_bmux8 g8(.sel0 (ctl[0]), .data0 (in_0[0]), .data1 (in_1[0]), .sel1 (ctl[1]), .data2 (in_2[0]), .data3 (in_3[0]), .sel2 (ctl[2]), .data4 (in_4[0]), .data5 (in_5[0]), .data6 (in_6[0]), .data7 (in_7[0]), .z (z[0]));
endmodule

module arith_unit(in_a, in_b, input_carry, alu_opcode, arith_out, flag_mux_out);
  input [7:0] in_a, in_b;
  input input_carry;
  input [2:0] alu_opcode;
  output [7:0] arith_out;
  output flag_mux_out;
  wire [7:0] in_a, in_b;
  wire input_carry;
  wire [2:0] alu_opcode;
  wire [7:0] arith_out;
  wire flag_mux_out;
  wire [7:0] add_out;
  wire [7:0] sub_out;
  wire [7:0] mul_out;
  wire [7:0] inc_out;
  wire [7:0] dec_out;
  wire [7:0] shift_out;
  wire add_cf, dec_cf, inc_cf, mul_of, shift_cf, sub_cf;
  fadder_8bit ADD_unit(.a (in_a), .b (in_b), .cin (input_carry), .s (add_out), .cout (add_cf));
  fsubtrator_8bit SUB_unit(.a (in_a), .b (in_b), .bin (input_carry), .d (sub_out), .bout (sub_cf));
  multiply MUL_unit(.in_a (in_a[3:0]), .in_b (in_b[3:0]), .mul_out (mul_out), .overflow (mul_of));
  fadder_8bit inc_unit(.a (in_a), .b (8'b1), .cin (input_carry), .s (inc_out), .cout (inc_cf));
  fsubtrator_8bit dec_unit(.a (in_a), .b (8'b1), .bin (input_carry), .d (dec_out), .bout (dec_cf));
  shifter_8bit SHIFT_unit(.in_a (in_a), .input_carry (input_carry), .opcode (alu_opcode), .shift_out (shift_out), .shift_cf (shift_cf));
  bmux mux_flag_mux_out_67_10(.ctl (alu_opcode), .in_0 (add_cf), .in_1 (sub_cf), .in_2 (mul_of), .in_3 (add_cf), .in_4 (sub_cf), .in_5 (shift_cf), .in_6 (shift_cf), .in_7 (1'b0), .z (flag_mux_out));
  bmux_2 mux_arith_out_67_10(.ctl (alu_opcode), .in_0 (add_out), .in_1 (sub_out), .in_2 (mul_out), .in_3 (inc_out), .in_4 (dec_out), .in_5 (shift_out), .in_6 (shift_out), .in_7 (8'b0), .z (arith_out));
endmodule

module compare_1bit(a, b, c1, c2, c3, y);
  input a, b, c1, c2, c3;
  output [2:0] y;
  wire a, b, c1, c2, c3;
  wire [2:0] y;
  wire n_2, n_5, n_7, n_8, n_9, n_10, n_11, n_13;
  not g1 (n_2, a);
  and g2 (n_5, n_2, b);
  and g3 (n_7, c2, n_5);
  or g4 (y[0], c1, n_7);
  xor g5 (n_8, a, b);
  not g6 (n_9, n_8);
  and g7 (y[1], c2, n_9);
  not g8 (n_10, b);
  and g9 (n_11, a, n_10);
  and g10 (n_13, c2, n_11);
  or g11 (y[2], c3, n_13);
endmodule

module compare_8bit(in_a, in_b, y);
  input [7:0] in_a, in_b;
  output [2:0] y;
  wire [7:0] in_a, in_b;
  wire [2:0] y;
  wire [2:0] y1;
  wire [2:0] y2;
  wire [2:0] y3;
  wire [2:0] y4;
  wire [2:0] y5;
  wire [2:0] y6;
  wire [2:0] y7;
  compare_1bit F0(.a (in_a[7]), .b (in_b[7]), .c1 (1'b0), .c2 (1'b1), .c3 (1'b0), .y (y1));
  compare_1bit F1(.a (in_a[6]), .b (in_b[6]), .c1 (y1[0]), .c2 (y1[1]), .c3 (y1[2]), .y (y2));
  compare_1bit F2(.a (in_a[5]), .b (in_b[5]), .c1 (y2[0]), .c2 (y2[1]), .c3 (y2[2]), .y (y3));
  compare_1bit F3(.a (in_a[4]), .b (in_b[4]), .c1 (y3[0]), .c2 (y3[1]), .c3 (y3[2]), .y (y4));
  compare_1bit F4(.a (in_a[3]), .b (in_b[3]), .c1 (y4[0]), .c2 (y4[1]), .c3 (y4[2]), .y (y5));
  compare_1bit F5(.a (in_a[2]), .b (in_b[2]), .c1 (y5[0]), .c2 (y5[1]), .c3 (y5[2]), .y (y6));
  compare_1bit F6(.a (in_a[1]), .b (in_b[1]), .c1 (y6[0]), .c2 (y6[1]), .c3 (y6[2]), .y (y7));
  compare_1bit F7(.a (in_a[0]), .b (in_b[0]), .c1 (y7[0]), .c2 (y7[1]), .c3 (y7[2]), .y (y));
endmodule

module and_op(A, B, Z);
  input [7:0] A, B;
  output [7:0] Z;
  wire [7:0] A, B;
  wire [7:0] Z;
  and g1 (Z[0], A[0], B[0]);
  and g2 (Z[1], A[1], B[1]);
  and g3 (Z[2], A[2], B[2]);
  and g4 (Z[3], A[3], B[3]);
  and g5 (Z[4], A[4], B[4]);
  and g6 (Z[5], A[5], B[5]);
  and g7 (Z[6], A[6], B[6]);
  and g8 (Z[7], A[7], B[7]);
endmodule

module or_op(A, B, Z);
  input [7:0] A, B;
  output [7:0] Z;
  wire [7:0] A, B;
  wire [7:0] Z;
  or g1 (Z[0], A[0], B[0]);
  or g2 (Z[1], A[1], B[1]);
  or g3 (Z[2], A[2], B[2]);
  or g4 (Z[3], A[3], B[3]);
  or g5 (Z[4], A[4], B[4]);
  or g6 (Z[5], A[5], B[5]);
  or g7 (Z[6], A[6], B[6]);
  or g8 (Z[7], A[7], B[7]);
endmodule

module xor_op(A, B, Z);
  input [7:0] A, B;
  output [7:0] Z;
  wire [7:0] A, B;
  wire [7:0] Z;
  xor g1 (Z[0], A[0], B[0]);
  xor g2 (Z[1], A[1], B[1]);
  xor g3 (Z[2], A[2], B[2]);
  xor g4 (Z[3], A[3], B[3]);
  xor g5 (Z[4], A[4], B[4]);
  xor g6 (Z[5], A[5], B[5]);
  xor g7 (Z[6], A[6], B[6]);
  xor g8 (Z[7], A[7], B[7]);
endmodule

module not_op(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module not_op_2(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module bmux_3(ctl, in_0, in_1, z);
  input ctl, in_0, in_1;
  output z;
  wire ctl, in_0, in_1;
  wire z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0), .data1 (in_1), .z (z));
endmodule

module logic_unit(in_a, in_b, alu_opcode, logic_out, comp_gt, comp_eq, comp_lt);
  input [7:0] in_a, in_b;
  input [2:0] alu_opcode;
  output [7:0] logic_out;
  output comp_gt, comp_eq, comp_lt;
  wire [7:0] in_a, in_b;
  wire [2:0] alu_opcode;
  wire [7:0] logic_out;
  wire comp_gt, comp_eq, comp_lt;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68;
  compare_8bit my_comparator(.in_a (in_a), .in_b (in_b), .y ({comp_gt, comp_eq, comp_lt}));
  and_op g1(.A (in_a), .B (in_b), .Z ({n_64, n_59, n_54, n_49, n_44, n_39, n_34, n_29}));
  or_op g2(.A (in_a), .B (in_b), .Z ({n_65, n_60, n_55, n_50, n_45, n_40, n_35, n_30}));
  xor_op g3(.A (in_a), .B (in_b), .Z ({n_66, n_61, n_56, n_51, n_46, n_41, n_36, n_31}));
  not_op g4(.A (in_a), .Z ({n_67, n_62, n_57, n_52, n_47, n_42, n_37, n_32}));
  not_op_2 g5(.A (in_b), .Z ({n_68, n_63, n_58, n_53, n_48, n_43, n_38, n_33}));
  bmux_3 mux_23_20(.ctl (comp_eq), .in_0 (1'b0), .in_1 (1'b1), .z (n_28));
  bmux_2 mux_logic_out_21_10(.ctl (alu_opcode), .in_0 ({7'b0, n_28}), .in_1 ({n_64, n_59, n_54, n_49, n_44, n_39, n_34, n_29}), .in_2 ({n_65, n_60, n_55, n_50, n_45, n_40, n_35, n_30}), .in_3 ({n_66, n_61, n_56, n_51, n_46, n_41, n_36, n_31}), .in_4 ({n_67, n_62, n_57, n_52, n_47, n_42, n_37, n_32}), .in_5 ({n_68, n_63, n_58, n_53, n_48, n_43, n_38, n_33}), .in_6 (8'b0), .in_7 (8'b0), .z (logic_out));
endmodule

module bmux_6(ctl, in_0, in_1, z);
  input ctl;
  input [7:0] in_0, in_1;
  output [7:0] z;
  wire ctl;
  wire [7:0] in_0, in_1;
  wire [7:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z (z[7]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z (z[6]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z (z[5]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z (z[4]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z (z[3]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z (z[2]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z (z[1]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z (z[0]));
endmodule

module ALU(in_a, in_b, input_carry, alu_opcode, alu_out, alu_out_flag);
  input [7:0] in_a, in_b;
  input input_carry;
  input [3:0] alu_opcode;
  output [7:0] alu_out;
  output [4:0] alu_out_flag;
  wire [7:0] in_a, in_b;
  wire input_carry;
  wire [3:0] alu_opcode;
  wire [7:0] alu_out;
  wire [4:0] alu_out_flag;
  wire [7:0] arith_out;
  wire [7:0] logic_out;
  wire flag_mux_out, n_13, n_44, n_45, n_46;
  arith_unit ari_module(.in_a (in_a), .in_b (in_b), .input_carry (input_carry), .alu_opcode (alu_opcode[2:0]), .arith_out (arith_out), .flag_mux_out (flag_mux_out));
  logic_unit logic_module(.in_a (in_a), .in_b (in_b), .alu_opcode (alu_opcode[2:0]), .logic_out (logic_out), .comp_gt (alu_out_flag[1]), .comp_eq (alu_out_flag[2]), .comp_lt (alu_out_flag[3]));
  bmux_3 mux_alu_out_flag_43_10(.ctl (alu_opcode[3]), .in_0 (flag_mux_out), .in_1 (1'b0), .z (alu_out_flag[4]));
  bmux_6 mux_alu_out_43_10(.ctl (alu_opcode[3]), .in_0 (arith_out), .in_1 (logic_out), .z (alu_out));
  nor g2 (n_45, alu_out[7], alu_out[6], alu_out[5], alu_out[4]);
  nor g3 (n_46, alu_out[3], alu_out[2], alu_out[1]);
  nand g4 (n_13, n_44, n_45, n_46);
  not g5 (alu_out_flag[0], n_13);
  not g6 (n_44, alu_out[0]);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX // captures one-hot property of select inputs
`ifdef BACK_TO_OLD_ONE_HOT
module CDN_mux3(sel0, data0, sel1, data1, sel2, data2, z);
  input sel0, data0, sel1, data1, sel2, data2;
  output z;
  wire sel0, data0, sel1, data1, sel2, data2;
  reg  z;
  always 
    @(sel0 or sel1 or sel2 or data0 or data1 or data2) 
      case ({sel0, sel1, sel2})
       3'b100: z = data0;
       3'b010: z = data1;
       3'b001: z = data2;
       default: z = 1'bX;
      endcase
endmodule
`else
module CDN_mux3(sel0, data0, sel1, data1, sel2, data2, z);
  input sel0, data0, sel1, data1, sel2, data2;
  output z;
  wire sel0, data0, sel1, data1, sel2, data2;
  wire z;
  wire w_0, w_1, w_2;
  and a_0 (w_0, sel0, data0);
  and a_1 (w_1, sel1, data1);
  and a_2 (w_2, sel2, data2);
  wire z_simple, sel_is_one_hot;
  or org (z_simple, w_0, w_1, w_2);
  assign sel_is_one_hot = $one_hot ({sel0, sel1, sel2});
  assign z = sel_is_one_hot ? z_simple : 1'bx;
endmodule
`endif // BACK_TO_OLD_ONE_HOT
`else
module CDN_mux3(sel0, data0, sel1, data1, sel2, data2, z);
  input sel0, data0, sel1, data1, sel2, data2;
  output z;
  wire sel0, data0, sel1, data1, sel2, data2;
  wire z;
  wire w_0, w_1, w_2;
  and a_0 (w_0, sel0, data0);
  and a_1 (w_1, sel1, data1);
  and a_2 (w_2, sel2, data2);
  or org (z, w_0, w_1, w_2);
endmodule
`endif // ONE_HOT_MUX
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux8(sel0, data0, data1, sel1, data2, data3, sel2, data4, data5, data6, data7, z);
  input sel0, data0, data1, sel1, data2, data3, sel2, data4, data5, data6, data7;
  output z;
  wire sel0, data0, data1, sel1, data2, data3, sel2, data4, data5, data6, data7;
  reg  z;
  always 
    @(sel0 or sel1 or sel2 or data0 or data1 or data2 or data3 or data4 or data5 or data6 or data7) 
      case ({sel0, sel1, sel2})
       3'b000: z = data0;
       3'b100: z = data1;
       3'b010: z = data2;
       3'b110: z = data3;
       3'b001: z = data4;
       3'b101: z = data5;
       3'b011: z = data6;
       3'b111: z = data7;
      endcase
endmodule
`else
module CDN_bmux8(sel0, data0, data1, sel1, data2, data3, sel2, data4, data5, data6, data7, z);
  input sel0, data0, data1, sel1, data2, data3, sel2, data4, data5, data6, data7;
  output z;
  wire sel0, data0, data1, sel1, data2, data3, sel2, data4, data5, data6, data7;
  wire z;
  wire inv_sel0, inv_sel1, inv_sel2, w_0, w_1, w_2, w_3, w_4;
  wire w_5, w_6, w_7;
  not i_0 (inv_sel0, sel0);
  not i_1 (inv_sel1, sel1);
  not i_2 (inv_sel2, sel2);
  and a_0 (w_0, inv_sel2, inv_sel1, inv_sel0, data0);
  and a_1 (w_1, inv_sel2, inv_sel1, sel0, data1);
  and a_2 (w_2, inv_sel2, sel1, inv_sel0, data2);
  and a_3 (w_3, inv_sel2, sel1, sel0, data3);
  and a_4 (w_4, sel2, inv_sel1, inv_sel0, data4);
  and a_5 (w_5, sel2, inv_sel1, sel0, data5);
  and a_6 (w_6, sel2, sel1, inv_sel0, data6);
  and a_7 (w_7, sel2, sel1, sel0, data7);
  or org (z, w_0, w_1, w_2, w_3, w_4, w_5, w_6, w_7);
endmodule
`endif // ONE_HOT_MUX
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
